# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hired.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 740)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-40, 0, 1101, 831))
        self.label.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(208, 139, 0)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("hired.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(530, 20, 381, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(470, 130, 131, 61))
        self.label_3.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(207, 138, 0)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(470, 230, 131, 61))
        self.label_4.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(207, 138, 0)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(470, 320, 141, 61))
        self.label_5.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(207, 138, 0)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(470, 410, 141, 61))
        self.label_6.setStyleSheet("font: 75 16pt \"Comic Sans MS\";color:rgb(207, 138, 0)")
        self.label_6.setObjectName("label_6")
        self.aptitude = QtWidgets.QLineEdit(Form)
        self.aptitude.setGeometry(QtCore.QRect(680, 130, 281, 51))
        self.aptitude.setStyleSheet("font: 75 italic 16pt \"Comic Sans MS\";color:rgb(0, 85, 127)")
        self.aptitude.setObjectName("aptitude")
        self.written = QtWidgets.QLineEdit(Form)
        self.written.setGeometry(QtCore.QRect(680, 230, 281, 51))
        self.written.setStyleSheet("font: 75 italic 16pt \"Comic Sans MS\";color:rgb(0, 85, 127)")
        self.written.setObjectName("written")
        self.interview = QtWidgets.QLineEdit(Form)
        self.interview.setGeometry(QtCore.QRect(680, 330, 281, 51))
        self.interview.setStyleSheet("font: 75 italic 16pt \"Comic Sans MS\";color:rgb(0, 85, 127)")
        self.interview.setObjectName("interview")
        self.cgpa = QtWidgets.QLineEdit(Form)
        self.cgpa.setGeometry(QtCore.QRect(680, 420, 281, 51))
        self.cgpa.setStyleSheet("font: 75 italic 16pt \"Comic Sans MS\";color:rgb(0, 85, 127)")
        self.cgpa.setObjectName("cgpa")
        self.check = QtWidgets.QPushButton(Form)
        self.check.setGeometry(QtCore.QRect(730, 510, 181, 51))
        self.check.setStyleSheet("font: 75 18pt \"Times New Roman\";color:rgb(255, 0, 0)")
        self.check.setObjectName("check")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(800, 610, 161, 91))
        self.label_7.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";color:rgb(0, 149, 0)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(590, 620, 131, 81))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("status.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.display = QtWidgets.QLabel(Form)
        self.display.setGeometry(QtCore.QRect(590, 620, 131, 81))
        self.display.setObjectName("display")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hiring_Status"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#0000ff;\">Hiring Status Prediction</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Aptitude</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Written</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Interview</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p>CGPA</p></body></html>"))
        self.check.setText(_translate("Form", "Check Status"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p>Hired- 1</p><p>Not Hired- 0</p></body></html>"))
        self.display.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
